### ISSUE TITLE
Great work, Makefiles?, new encryption?

### ISSUE THREAD

**Issue by bm16ton** [RadioOperator/Yet_Another_Bootloader#2]
Hello, Great work!! Tho a few questions;
I assume .uvprojx files are from something like Keil or another pay for closed source IDE, any chance they can export Makefiles? I can write them but I have mixed results when doing so on .uvprojx based firmwares.
Also I ordered a new stlink-v3mods and micro from digi-key and both had the newest firmware already applied (or close to). Only the newest firmware updater for the micro would see the micro (fail id match) and refuses to load the firmware with encryption sha256 digest error. Unfortunately dont have it in front of me for exact error, but will follow up. The mods board I cannot find any  updater that finds it, so Im afraid im stuck until the newer updater comes out with whatever ids its looking for builtin. (My assumption is the newest update changed id, so only future versions can find it?) 
Just didn't know if they managed to change encryption stuff in newer/newest firmware's and everyone but me already knew. But my board with older firmware is working great! love the multi-app option, always wanted that! 
And in the other issue posted about the usb2serial, it breaks into a language I don't know, is the link at end to a fixed version? Any chance of the source?

**Comment by RadioOperator** [comment]
Hi, I'm trying to answer your questions:
1. port to other IDEs, should be very difficult. My source code based ARM-Keil + RTE + STM32Cube and AC6, can not convert to makefile easily. Also because of the USB library issues, any changes, almost like create a new project.
2. I did this project around 2 years ago, for now, I donot know what's happened on newer STLINK-V3 boards. I think you already read this link: https://github.com/RadioOperator/CMSIS-DAP_for_STLINK-V3MINI/issues/1
that's the project story.

**Comment by bm16ton** [comment]
Yes I did read that link very helpful! I wonder if I post the new errors if anyone would respond? Thank you again for this awesome work! And very timely response!

**Comment by RadioOperator** [comment]
@bm16ton  Hi,
3. about the usb2serial (VCP) issue, it's a special use case: before the DAP board power-ON, connected it to a "hot" UART port, after DAP power-ON, the VCP will not work completely OK.
In the attached code, I changed the VCP uart driver from INT mode to DMA mode. Because I did not get any feedback from the issue reporter, I donot know if new code is OK or not, so no further follow-up.
